module.exports = {
    file: 'dist/main.js',
    icon: 'apps/server/src/assets/images/tail.ico',
    name: 'fbw-simbridge',
    description: 'FlyByWire Simbridge',
    company: 'FlyByWire Simulations',
    version: '0.4.0',
    copyright: 'GNU v3',
    pkg: {
        targets: [
            'node16-win-x64',
        ],
        assets: [
            'node_modules/linebreak/src/classes.trie',
            'node_modules/sharp/**/*.*',
            'node_modules/skia-canvas/**/*.*',
            'node_modules/canvas/**/*.*',
            'node_modules/pdfkit/js/data/Helvetica.afm',
            'node_modules/swagger-ui-dist/**/*.*',
            'node_modules/gpu.js/**/*.*',
            'node_modules/gl/**/*.*',
            'node_modules/gl-wiretap/**/*.*',
            'node_modules/glsl-tokenizer/**/*.*',
            'node_modules/gpu-mock.js/**/*.*',
            'node_modules/bindings/**/*.*',
            'node_modules/file-uri-to-path/**/*.*',
            'node_modules/bit-twiddle/**/*.*',
            'node_modules/bit-twiddle/**/*.*',
            'node_modules/@flybywiresim/msfs-nodejs/**/*.*',
            'dist/mcdu/**/*',
            'dist/assets/**/*',
            'dist/terrain/mapdata/**/*.*',
            'dist/terrain/processing/**/*.*',
            'dist/terrain/communication/**/*.*',
            'dist/terrain/fileformat/**/*.*',
            'build/SimConnect.dll',
        ],
        outputPath: 'build',
    },
};
