module.exports = {
    file: 'dist/main.js',
    icon: 'apps/server/src/assets/images/tail.ico',
    name: 'fbw-simbridge',
    description: 'FlyByWire Simbridge',
    company: 'FlyByWire Simulations',
    version: '0.3.20',
    copyright: 'GNU v3',
    pkg: {
        targets: [
            'node16-win-x64',
        ],
        assets: [
            'node_modules/linebreak/src/classes.trie',
            'node_modules/skia-canvas/**/*.*',
            'node_modules/canvas/**/*.*',
            'node_modules/pdfkit/js/data/Helvetica.afm',
            'node_modules/swagger-ui-dist/**/*.*',
            'node_modules/gpu.js/**/*.*',
            'node_modules/gl/index.js',
            'node_modules/gl/src/**/*.js',
            'node_modules/gl/build/Release/*.*',
            'node_modules/gl/deps/windows/dll/x64/*.*',
            'node_modules/glsl-tokenizer/*.js',
            'node_modules/glsl-tokenizer/lib/*.js',
            'node_modules/gpu-mock.js/**/*.js',
            'node_modules/bindings/**/*.js',
            'node_modules/bit-twiddle/*.js',
            'dist/mcdu/**/*',
            'dist/assets/**/*',
            'dist/terrain/mapdata/maploader.js',
            'dist/terrain/processing/**/*.js',
            'build/SimConnect.dll',
        ],
        outputPath: 'build',
    },
};
