// define the low density pattern
export const LowDensityPattern = [
    {
        angleRanges: [[0, 90]],
        minPixelDistance: 0,
        patterns: [
            [
                [],
                [],
                [],
                [0, 8, 10, 11],
                [],
                [],
                [],
                [],
                [],
                [2, 3, 11, 12],
                [],
                [],
                [],
            ],
            [
                [],
                [],
                [],
                [],
                [],
                [6, 7],
                [],
                [],
                [],
                [],
                [],
                [],
                [1, 12],
            ],
            [
                [2, 6, 10, 11],
                [],
                [],
                [],
                [],
                [],
                [2, 5, 6, 12],
                [],
                [],
                [],
                [],
                [],
                [11],
            ],
        ],
    },
];
